// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pxl8.ControlApi.Data;

#nullable disable

namespace Pxl8.ControlApi.Data.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    partial class ControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pxl8.ControlApi.Data.Entities.BillingPeriod", b =>
                {
                    b.Property<Guid>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<long>("BandwidthConsumedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bandwidth_consumed_bytes");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period_key");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TransformsConsumed")
                        .HasColumnType("integer")
                        .HasColumnName("transforms_consumed");

                    b.HasKey("PeriodId");

                    b.HasIndex("TenantId", "PeriodKey")
                        .HasDatabaseName("ix_billing_periods_tenant_period_key");

                    b.ToTable("billing_periods", (string)null);
                });

            modelBuilder.Entity("Pxl8.ControlApi.Data.Entities.BudgetLease", b =>
                {
                    b.Property<Guid>("LeaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<long>("BandwidthGrantedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bandwidth_granted_bytes");

                    b.Property<string>("DataplaneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dataplane_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TransformsGranted")
                        .HasColumnType("integer")
                        .HasColumnName("transforms_granted");

                    b.HasKey("LeaseId");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_leases_request_id");

                    b.HasIndex("TenantId", "PeriodId", "DataplaneId")
                        .IsUnique()
                        .HasDatabaseName("ix_budget_leases_active_unique")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("TenantId", "PeriodId", "DataplaneId", "Status")
                        .HasDatabaseName("ix_budget_leases_tenant_period_dataplane_status");

                    b.ToTable("budget_leases", (string)null);
                });

            modelBuilder.Entity("Pxl8.ControlApi.Data.Entities.UsageReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<long>("BandwidthUsedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bandwidth_used_bytes");

                    b.Property<string>("DataplaneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dataplane_id");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TransformsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("transforms_used");

                    b.HasKey("ReportId");

                    b.HasIndex("ReportId")
                        .IsUnique()
                        .HasDatabaseName("ix_usage_reports_report_id");

                    b.HasIndex("TenantId", "PeriodId", "ReceivedAt")
                        .HasDatabaseName("ix_usage_reports_tenant_period_received");

                    b.ToTable("usage_reports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
